/*
-- Query: SELECT * FROM `coffee-shop`.new
LIMIT 0, 1000

-- Date: 2021-07-05 20:34
*/
INSERT INTO `` (`id_pro`,`name`,`info`,`image`) VALUES (13,'MờI BạN DùNG THử Cà PHê SữA đá HOà TAN - SảN PHẩM HOàN TOàN MớI Từ NHà!','Cà phê sữa đá hoà tan MỚI, muốn là có, pha ngay tại nhà mà vẫn đúng gu, thơm ngon, đậm vị. \n \n\nMỗi gói Cà phê sữa đá hoà tan là công thức hoàn hảo cho một ly cà phê sữa thơm ngon, chuẩn chỉnh giúp bạn tỉnh táo và hứng khởi cho một ngày làm việc thật hiệu quả.\n\n\nƯU ĐÃI GIÁ DÙNG THỬ:\n\nVới mỗi hóa đơn từ 50.000đ, bạn sẽ được mua 01 hộp 10 gói Cà phê sữa đá hoà tan với giá ưu đãi 29.000đ (giá gốc 44.000đ).\n\n????Áp dụng trên App TCH và mua tại Cửa hàng (trừ TCH Signature, TCH Vin Wonders, Grand World, Hòn Thơm, Bà Đen)\n\n????Thời gian bắt đầu: từ 19/06 đến 30/06.\n\n????Ưu đãi không áp dụng lũy tiến và không áp dụng song song với các chương trình khuyến mãi khác.','Khuyến mãi.gif');
INSERT INTO `` (`id_pro`,`name`,`info`,`image`) VALUES (14,'SỰ KIỆN TIẾP THEO','Chương trình Acoustic Hàng tuần thứ 3-5-7-Cn lúc 20h-Địa chỉ 44e Pasteur Q1.p bến nghé Q1\n_Là nơi Âm Thầm của cảm xúc dành cho tất cả mọi người bộc lộ xúc cảm của mình! Thoải mái ca hát mà không phụ thu,\n_giá chỉ từ 40.000vnd-70.000vnd\n* Ngoài ra Sâm Acoustic Coffee\n* (Cho Thuê )\n* Âm thanh,Ánh Sáng & Band nhạc\n* [Nhận tổ chức và Cho thuê]\n* Không gian pha trộn giữa Undeground & Acoustic\n* Sức chứa trên 100ng cùng Âm thanh chuẩn\n* Phù hợp tổ chức show-sự kiện -party-sinh nhật-hội họp\n* Hỗ trợ các CLB tổ chức sự kiện với giá hợp lý','sukien.png');
INSERT INTO `` (`id_pro`,`name`,`info`,`image`) VALUES (15,'SẢN PHẨM MớI','Đá bào ở đây phải nói siêu mịn và nhuyễn, hoà lẫn với sữa tươi thơm béo ngậy ngất ngây kèm theo topping hạnh nhân và bánh phô mai thì ngon không cưỡng nổi. Thường cứ một phần sẽ kèm theo một viên kem vị sữa đặt trên đỉnh nhìn rất thích và ngon mắt.\nVề không gian của quán thì vừa đủ, không rộng quá cũng không chật, bàn ghế được sắp xếp gọn gàng, sạch sẽ. Đồ dùng làm bằng gỗ mộc mạc nên tạo cho khách hàng cảm giác rất ấm áp và gần gũi.\n\n\n\nThực đơn của quán có rất nhiều món cho bạn lựa chọn như Bingsu đậu đỏ, matcha, dừa, xoài, cherry,…mỗi món có một vị ngon riêng mà món nào cũng tròn vị, vị sữa ngọt nhẹ thanh mát ăn không hề bị ngậy, trái cây thì tươi ngon vừa miệng, dưới là đá bào từ sữa, trên có phủ bột đậu nành bùi bùi và topping bánh gạo injeolmi dẻo mềm.','dcv_large.jpg');
